import { Product, Category, FAQItem } from '../types';

export const MOCK_CATEGORIES: Category[] = [
  {
    id: 'cat-flower',
    name: 'Craft Flower',
    slug: 'flower',
    description: 'Ultra-premium, small-batch craft cannabis buds hand-selected for high terpene profiles and potency.',
    image: 'https://images.unsplash.com/photo-1603909223429-69bb7101f420?auto=format&fit=crop&w=800&q=80',
    count: 24,
    featured: true,
  },
  {
    id: 'cat-concentrates',
    name: 'Concentrates & Rosin',
    slug: 'concentrates',
    description: 'Solventless live rosin, live resin diamond diamonds, and terpene rich extracts.',
    image: 'https://images.unsplash.com/photo-1512069772995-ec65ed45afd6?auto=format&fit=crop&w=800&q=80',
    count: 16,
    featured: true,
  },
  {
    id: 'cat-thc-pens',
    name: 'THC Vapes & Pens',
    slug: 'thc-pens',
    description: 'Discreet, ceramic-core live resin cartridges and rechargeable all-in-one vapes.',
    image: 'https://images.unsplash.com/photo-1527661591475-527312dd65f5?auto=format&fit=crop&w=800&q=80',
    count: 18,
    featured: true,
  },
  {
    id: 'cat-edibles',
    name: 'Edibles & Artisanal Gummies',
    slug: 'edibles',
    description: 'Chef-curated gourmet fruit chews, botanical tinctures, and Belgian dark chocolate bars.',
    image: 'https://images.unsplash.com/photo-1582058091505-f87a2e55a40f?auto=format&fit=crop&w=800&q=80',
    count: 20,
    featured: true,
  },
  {
    id: 'cat-pre-rolls',
    name: 'Pre-Rolls & Accessories',
    slug: 'pre-rolls',
    description: 'Infused pre-roll multi-packs, diamond dust rolls, and precision gold leaf smoking accessories.',
    image: 'https://images.unsplash.com/photo-1508746829417-e6f548d8d6ed?auto=format&fit=crop&w=800&q=80',
    count: 14,
    featured: true,
  },
  {
    id: 'cat-mushrooms',
    name: 'Microdose Mushrooms',
    slug: 'mushrooms',
    description: 'Premium functional microdose capsules and organic botanical mushroom tea blends.',
    image: 'https://images.unsplash.com/photo-1543332164-6e82f355badc?auto=format&fit=crop&w=800&q=80',
    count: 8,
    featured: true,
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    slug: 'velvet-kush-craft-flower',
    name: 'Velvet Kush Reserve',
    tagline: 'Private Reserve Small Batch Craft Flower',
    category: 'Craft Flower',
    categorySlug: 'flower',
    price: 44.99,
    regularPrice: 49.99,
    salePrice: 44.99,
    onSale: true,
    featured: true,
    inStock: true,
    stockQuantity: 45,
    strainType: 'Indica',
    thcPercentage: 31.5,
    cbdPercentage: 0.1,
    effects: ['Deep Relaxation', 'Euphoric', 'Nighttime Calm'],
    aroma: ['Pine Needle', 'Vanilla Terpenes', 'Earth Musk'],
    defaultWeight: '3.5g',
    weightOptions: [
      { label: '3.5g', grams: 3.5, price: 44.99, salePrice: 44.99, inStock: true },
      { label: '7g', grams: 7, price: 82.99, salePrice: 79.99, inStock: true },
      { label: '14g', grams: 14, price: 154.99, salePrice: 145.99, inStock: true },
      { label: '28g (1 oz)', grams: 28, price: 279.99, salePrice: 259.99, inStock: true },
    ],
    shortDescription: 'Cured for 45 days in dark glass cellars, Velvet Kush delivers velvety dense buds covered in glistening crystalline trichomes.',
    description: 'Cultivated in micro-climate greenhouse facilities in coastal British Columbia, Velvet Kush Reserve represents the peak of modern craft cannabis. Every flower is hand-trimmed, cold-cured for six full weeks, and packaged in UV-resistant frosted matte black glass jars with double silicone freshness seals.',
    images: [
      'https://images.unsplash.com/photo-1603909223429-69bb7101f420?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1512069772995-ec65ed45afd6?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1527661591475-527312dd65f5?auto=format&fit=crop&w=1000&q=80',
    ],
    attributes: [
      { name: 'Harvest Date', options: ['June 2026'] },
      { name: 'Cure Time', options: ['45 Days Cold Cure'] },
      { name: 'Dominant Terpenes', options: ['Myrcene', 'Caryophyllene', 'Limonene'] },
    ],
    rating: 4.95,
    reviewCount: 38,
    badge: 'Bestseller',
    reviews: [
      {
        id: 'rev-1',
        author: 'Marcus V., Abbotsford',
        rating: 5,
        date: '2026-07-18',
        comment: 'Delivered to my door in East Abbotsford in under 45 minutes! Smells divine and cured to perfection.',
        verifiedBuyer: true,
      },
      {
        id: 'rev-2',
        author: 'Elena R., Mission',
        rating: 5,
        date: '2026-07-12',
        comment: 'Hands down the best flower available in Fraser Valley. EliteBud customer service is top tier.',
        verifiedBuyer: true,
      }
    ]
  },
  {
    id: 'prod-2',
    slug: 'gold-tier-live-rosin',
    name: 'Gold Tier Solventless Live Rosin',
    tagline: 'Cold Cured Fresh Frozen Hash Rosin',
    category: 'Concentrates & Rosin',
    categorySlug: 'concentrates',
    price: 69.99,
    regularPrice: 69.99,
    onSale: false,
    featured: true,
    inStock: true,
    stockQuantity: 28,
    strainType: 'Hybrid',
    thcPercentage: 78.4,
    cbdPercentage: 0.8,
    effects: ['Elevated Focus', 'Smooth Body High', 'Creative Energy'],
    aroma: ['Fresh Cut Lemon', 'Sweet Gasoline', 'Floral Terps'],
    defaultWeight: '1g',
    weightOptions: [
      { label: '1g', grams: 1, price: 69.99, inStock: true },
      { label: '2g Jar', grams: 2, price: 129.99, inStock: true },
    ],
    shortDescription: 'First wash 73u-120u ice water hash pressed at low temperature for a translucent, butter-like consistency.',
    description: 'Gold Tier Live Rosin is created purely with ice water, heat, and pressure. Zero solvents or chemical additives are ever involved. Made exclusively from whole-plant fresh frozen trichome heads collected during initial wash cycles.',
    images: [
      'https://images.unsplash.com/photo-1512069772995-ec65ed45afd6?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1603909223429-69bb7101f420?auto=format&fit=crop&w=1000&q=80',
    ],
    attributes: [
      { name: 'Extraction', options: ['100% Solventless Ice Water Hash'] },
      { name: 'Micron Screen', options: ['73u - 120u First Wash'] },
    ],
    rating: 5.0,
    reviewCount: 24,
    badge: 'Limited Batch',
    reviews: [
      {
        id: 'rev-3',
        author: 'David K., Chilliwack',
        rating: 5,
        date: '2026-07-20',
        comment: 'Incredible flavor and purity. Extremely clean dab experience.',
        verifiedBuyer: true,
      }
    ]
  },
  {
    id: 'prod-3',
    slug: 'sapphire-diesel-vape',
    name: 'Sapphire Diesel Live Resin Cartridge',
    tagline: 'Custom Ceramic Core High-Terpene Vape',
    category: 'THC Vapes & Pens',
    categorySlug: 'thc-pens',
    price: 52.99,
    regularPrice: 59.99,
    salePrice: 52.99,
    onSale: true,
    featured: true,
    inStock: true,
    stockQuantity: 60,
    strainType: 'Sativa',
    thcPercentage: 84.2,
    cbdPercentage: 0.2,
    effects: ['Daytime Energy', 'Uplifting Mood', 'Social Clarity'],
    aroma: ['Sour Citrus', 'Diesel Fuel', 'Grapefruit Zest'],
    defaultWeight: '1.0g',
    weightOptions: [
      { label: '1.0g Cart', grams: 1, price: 52.99, salePrice: 52.99, inStock: true },
      { label: '2-Pack Bundle', grams: 2, price: 94.99, salePrice: 89.99, inStock: true },
    ],
    shortDescription: 'Full-spectrum liquid live resin filled inside medical-grade zirconia ceramic hardware for pure untainted vapor.',
    description: ' Sapphire Diesel pairs high sativa terpene retention with custom engineered ceramic heating elements. No heavy metals, no artificial flavor additives, no cutting agents. Pure unadulterated live resin extract.',
    images: [
      'https://images.unsplash.com/photo-1527661591475-527312dd65f5?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1508746829417-e6f548d8d6ed?auto=format&fit=crop&w=1000&q=80',
    ],
    attributes: [
      { name: 'Hardware', options: ['Medical Zirconia Ceramic 510 Thread'] },
      { name: 'Extract Type', options: ['Full Spectrum Live Resin'] },
    ],
    rating: 4.88,
    reviewCount: 19,
    badge: 'Staff Pick',
    reviews: []
  },
  {
    id: 'prod-4',
    slug: 'artisan-pomegranate-gummies',
    name: 'Artisanal Pomegranate & Yuzu Gummies (200mg)',
    tagline: 'Chef Crafted Fast-Acting Nano Edibles',
    category: 'Edibles & Artisanal Gummies',
    categorySlug: 'edibles',
    price: 32.99,
    regularPrice: 32.99,
    onSale: false,
    featured: true,
    inStock: true,
    stockQuantity: 80,
    strainType: 'Hybrid',
    thcPercentage: 10.0, // 10mg per piece x 20
    cbdPercentage: 2.0,
    effects: ['Balanced Euphoria', 'Stress Relief', 'Gentle Body Tingles'],
    aroma: ['Tart Pomegranate', 'Yuzu Citrus', 'Organic Cane Sugar'],
    defaultWeight: '20 Pieces (200mg Total)',
    weightOptions: [
      { label: '200mg Pack (20 Gummies)', grams: 100, price: 32.99, inStock: true },
      { label: 'Double Pack (400mg Total)', grams: 200, price: 58.99, inStock: true },
    ],
    shortDescription: 'Infused with fast-acting nano-emulsified rosin for consistent onset in 15–20 minutes.',
    description: 'Crafted in small batches by culinary pastry chefs, using real organic fruit purée, natural tapioca syrup, and solventless live rosin. Enhanced with nano-emulsification technology for ultra-rapid absorption.',
    images: [
      'https://images.unsplash.com/photo-1582058091505-f87a2e55a40f?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1543332164-6e82f355badc?auto=format&fit=crop&w=1000&q=80',
    ],
    attributes: [
      { name: 'Onset Time', options: ['15 – 25 Minutes Fast-Acting'] },
      { name: 'Dietary', options: ['Vegan', 'Gluten Free', 'Non-GMO'] },
    ],
    rating: 4.92,
    reviewCount: 42,
    badge: 'Bestseller',
    reviews: []
  },
  {
    id: 'prod-5',
    slug: 'diamond-infused-prerolls',
    name: 'Diamond Infused Pre-Roll 5-Pack',
    tagline: 'Whole Flower Rolled with THCA Diamonds & Rosin',
    category: 'Pre-Rolls & Accessories',
    categorySlug: 'pre-rolls',
    price: 49.99,
    regularPrice: 54.99,
    salePrice: 49.99,
    onSale: true,
    featured: true,
    inStock: true,
    stockQuantity: 35,
    strainType: 'Indica',
    thcPercentage: 42.0,
    cbdPercentage: 0.1,
    effects: ['Heavy Relaxation', 'Couchlock', 'End of Day Unwind'],
    aroma: ['Rich Hashish', 'Pine Bark', 'Gas'],
    defaultWeight: '5 x 0.7g (3.5g Total)',
    weightOptions: [
      { label: '5-Pack (3.5g)', grams: 3.5, price: 49.99, salePrice: 49.99, inStock: true },
      { label: '10-Pack Box Set (7g)', grams: 7, price: 89.99, salePrice: 84.99, inStock: true },
    ],
    shortDescription: '100% whole flower, hand-infused with crushed pure THCA diamonds and brushed with live resin distillate.',
    description: 'No trim, no shake, no stems. Only single-origin top-tier flower infused with micro-milled THCA diamonds. Wrapped in unbleached organic Dutch hemp papers with spiral glass filter tips.',
    images: [
      'https://images.unsplash.com/photo-1508746829417-e6f548d8d6ed?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1603909223429-69bb7101f420?auto=format&fit=crop&w=1000&q=80',
    ],
    attributes: [
      { name: 'Paper', options: ['Unbleached Organic Dutch Hemp'] },
      { name: 'Tip', options: ['Reusable Glass Tip'] },
    ],
    rating: 4.97,
    reviewCount: 31,
    badge: 'New Release',
    reviews: []
  },
  {
    id: 'prod-6',
    slug: 'clarity-microdose-capsules',
    name: 'Clarity Nootropic Mushroom Microdose (30 Caps)',
    tagline: 'Organic Golden Teacher + Lion’s Mane Blend',
    category: 'Microdose Mushrooms',
    categorySlug: 'mushrooms',
    price: 59.99,
    regularPrice: 59.99,
    onSale: false,
    featured: false,
    inStock: true,
    stockQuantity: 40,
    strainType: 'N/A',
    thcPercentage: 0,
    cbdPercentage: 0,
    effects: ['Cognitive Clarity', 'Mood Elevation', 'Focus Boost'],
    aroma: ['Earth', 'Earthy Tea', 'Cocoa'],
    defaultWeight: '30 Vegan Capsules',
    weightOptions: [
      { label: '30 Bottle (100mg/cap)', grams: 3, price: 59.99, inStock: true },
      { label: '60 Bottle (100mg/cap)', grams: 6, price: 99.99, inStock: true },
    ],
    shortDescription: 'Precisely dosed 100mg organic mushroom fruit body combined with 200mg dual-extracted organic Lion’s Mane.',
    description: 'Formulated for subtle daily cognitive enhancement without perceptual disruption. Manufactured in ISO-certified cleanroom facilities using 100% fruiting body extracts.',
    images: [
      'https://images.unsplash.com/photo-1543332164-6e82f355badc?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1582058091505-f87a2e55a40f?auto=format&fit=crop&w=1000&q=80',
    ],
    attributes: [
      { name: 'Dosage', options: ['100mg Golden Teacher + 200mg Lion’s Mane per Capsule'] },
    ],
    rating: 4.90,
    reviewCount: 15,
    badge: 'Staff Pick',
    reviews: []
  }
];

export const MOCK_FAQS: FAQItem[] = [
  {
    id: 'faq-1',
    category: 'Delivery',
    question: 'How fast is same-day delivery in Abbotsford?',
    answer: 'Orders placed within our business hours (10:00 AM – 11:00 PM) are delivered directly to your doorstep in approximately 1 to 3 hours across Abbotsford, Mission, Chilliwack, Aldergrove, and Langley Township.',
  },
  {
    id: 'faq-2',
    category: 'Delivery',
    question: 'What are the delivery fees and free delivery minimums?',
    answer: 'Delivery is FREE on all orders over $50 CAD in Abbotsford and surrounding core areas. For orders under $50, a nominal $10 flat delivery fee applies.',
  },
  {
    id: 'faq-3',
    category: 'Payments',
    question: 'What payment methods do you accept?',
    answer: 'We accept instant Interac E-Transfer (auto-deposit sent to safepayabby@gmail.com) and exact Cash On Delivery upon driver arrival.',
  },
  {
    id: 'faq-4',
    category: 'Promotions',
    question: 'How do I claim the FREE 7g Weed Google Review promotion?',
    answer: 'Simply leave a verified 5-star Google review for EliteBud. Show your review confirmation to your delivery driver or include your Google name in your order notes, and we will add a complimentary 7g craft flower reward to your delivery!',
  },
  {
    id: 'faq-5',
    category: 'Products',
    question: 'Are all products verified for quality and freshness?',
    answer: 'Yes. All flower and concentrates are stored in humidity-controlled sealed glass containers and cured under laboratory conditions to ensure peak terpene preservation and moisture levels.',
  },
  {
    id: 'faq-6',
    category: 'Hours',
    question: 'What are EliteBud’s dispatch operating hours?',
    answer: 'Our dispatch and delivery drivers operate daily 7 days a week from 10:00 AM until 11:00 PM PST. You can also schedule advance orders outside business hours for morning fulfillment.',
  }
];
